name: deploy page

on:
  push:
    branches:
      - 'main'

jobs:
  FrontDeploy:
    name: FrontDeploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install

    - name: deploy to Heroku
      run:
        git push heroku main
        heroku ps:scale web=1
        heroku open